// <auto-generated />
using BigFile.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace BigFile.DataAccess.Migrations
{
    [DbContext(typeof(BigFileDbContext))]
    partial class BigFileDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("BigFile.DataAccess.BigFile", b =>
                {
                    b.Property<int>("BigFileId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationTime");

                    b.Property<string>("FileName")
                        .HasMaxLength(256);

                    b.Property<string>("FilePath")
                        .HasMaxLength(256);

                    b.Property<DateTime>("LastWriteTime");

                    b.Property<long>("Length");

                    b.HasKey("BigFileId");

                    b.ToTable("BigFiles");
                });

            modelBuilder.Entity("BigFile.DataAccess.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ExceptionLog")
                        .HasMaxLength(4096);

                    b.Property<string>("ExceptionMessage")
                        .HasMaxLength(1024);

                    b.Property<string>("FilePath")
                        .HasMaxLength(256);

                    b.Property<string>("FolderPath")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
